// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化 GPU 渲染器
/// 返回 0 表示成功，返回 -1 表示失败
int gpuInit() => RustLib.instance.api.crateApiGpuApiGpuInit();

/// 渲染波形到纹理（GPU 加速），并返回 RGBA 数据
/// 参数：
/// - width: 纹理宽度
/// - height: 纹理高度
/// - points: 波形数据点数组（x, y 交替，归一化到 [0, 1]）
/// - point_count: 点数
/// - r, g, b, a: RGBA 颜色（0-255）
/// 返回：RGBA 字节数组（长度 = width * height * 4），失败返回空数组
Uint8List gpuRenderWaveform({
  required int width,
  required int height,
  required List<double> points,
  required int pointCount,
  required int r,
  required int g,
  required int b,
  required int a,
}) => RustLib.instance.api.crateApiGpuApiGpuRenderWaveform(
  width: width,
  height: height,
  points: points,
  pointCount: pointCount,
  r: r,
  g: g,
  b: b,
  a: a,
);

/// 释放 GPU 渲染器
void gpuCleanup() => RustLib.instance.api.crateApiGpuApiGpuCleanup();
