// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `eval`, `execute_script`, `fire_sys_timer`, `get_lua_engine`, `get_scripts_dir`, `load_core_scripts`, `lock_mutex`, `new`, `new`, `register_basic_api`, `set_device_id`, `trigger_callback_inner`, `trigger_callbacks`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CALLBACKS`, `INPUT_BOX_RESPONSES`, `INPUT_BOX_STATE`, `InputBoxRequest`, `InputBoxState`, `LUA_ENGINE`, `LuaEngine`, `TIMER_TASKS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `deref`, `deref`, `deref`, `initialize`, `initialize`, `initialize`, `initialize`, `initialize`

/// 初始化 Lua 引擎
Future<void> initLuaEngine() =>
    RustLib.instance.api.crateApiLuaApiInitLuaEngine();

/// FFI 接口:执行 Lua 脚本
bool luaExecuteScript({required String script}) =>
    RustLib.instance.api.crateApiLuaApiLuaExecuteScript(script: script);

/// FFI 接口:评估 Lua 表达式
String luaEval({required String expression}) =>
    RustLib.instance.api.crateApiLuaApiLuaEval(expression: expression);

/// FFI 接口:设置 Lua 引擎当前设备 ID
bool luaSetDeviceId({required String deviceId}) =>
    RustLib.instance.api.crateApiLuaApiLuaSetDeviceId(deviceId: deviceId);

/// 触发指定通道的 Lua 回调(公共接口,供其他模块调用)
/// 通过 tiggerCB(-1, channel, data) 触发通道回调
/// 整个回调链都包裹在 AssertUnwindSafe 中,即使 Lua 侧 panic 也不会崩溃
Future<void> triggerCallback({
  required String channel,
  required List<int> data,
}) => RustLib.instance.api.crateApiLuaApiTriggerCallback(
  channel: channel,
  data: data,
);

/// FFI 接口:读取 Lua 日志缓冲区(同时清空,避免重复消费)
List<String> luaGetLogs() => RustLib.instance.api.crateApiLuaApiLuaGetLogs();

/// FFI 接口:清空 Lua 日志缓冲区
void luaClearLogs() => RustLib.instance.api.crateApiLuaApiLuaClearLogs();

/// FFI 接口:检查是否有 InputBox 请求
String? luaPollInputBox() =>
    RustLib.instance.api.crateApiLuaApiLuaPollInputBox();

/// FFI 接口:响应 InputBox 请求
bool luaRespondInputBox({required BigInt id, required String value}) =>
    RustLib.instance.api.crateApiLuaApiLuaRespondInputBox(id: id, value: value);

/// FFI 接口:获取脚本列表
List<String> luaGetScriptsList() =>
    RustLib.instance.api.crateApiLuaApiLuaGetScriptsList();

/// FFI 接口:加载脚本内容
String luaLoadScript({required String name}) =>
    RustLib.instance.api.crateApiLuaApiLuaLoadScript(name: name);

/// FFI 接口:保存脚本内容
bool luaSaveScript({required String name, required String content}) => RustLib
    .instance
    .api
    .crateApiLuaApiLuaSaveScript(name: name, content: content);

/// FFI 接口:删除脚本
bool luaDeleteScript({required String name}) =>
    RustLib.instance.api.crateApiLuaApiLuaDeleteScript(name: name);

/// FFI 接口:打开脚本目录
bool luaOpenScriptsFolder() =>
    RustLib.instance.api.crateApiLuaApiLuaOpenScriptsFolder();
