// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/virtual_device/simulator.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

VirtualInfraStatus startVirtualInfrastructure() =>
    RustLib.instance.api.crateApiVirtualApiStartVirtualInfrastructure();

bool stopVirtualInfrastructure() =>
    RustLib.instance.api.crateApiVirtualApiStopVirtualInfrastructure();

VirtualInfraStatus getVirtualInfraStatus() =>
    RustLib.instance.api.crateApiVirtualApiGetVirtualInfraStatus();

bool isVirtualSerialRunning() =>
    RustLib.instance.api.crateApiVirtualApiIsVirtualSerialRunning();
