name: vcr
description: "VCR V0.0.6 - Virtual Instrument Control Application"
publish_to: 'none'

version: 0.0.6+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_rust_bridge: ^2.12.0
  rust_lib_vcr:
    path: rust_builder
  file_picker: ^8.0.0
  gbk_codec: ^0.4.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  ffi: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DS-Digital
      fonts:
        - asset: assets/fonts/DS-DIGI.TTF
          weight: 400
        - asset: assets/fonts/DS-DIGIB.TTF
          weight: 700
        - asset: assets/fonts/DS-DIGII.TTF
          style: italic
        - asset: assets/fonts/DS-DIGIT.TTF
