// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/debug_api.dart';
import 'api/device_api.dart';
import 'api/gpu_api.dart';
import 'api/lua_api.dart';
import 'api/plot_api.dart';
import 'api/virtual_api.dart';
import 'core/device/models.dart';
import 'core/session/debug_session.dart';
import 'core/virtual_device/simulator.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, List<PlotPoint>> dco_decode_Map_String_list_plot_point_None(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DeviceInfo dco_decode_box_autoadd_device_info(dynamic raw);

  @protected
  ConnectionType dco_decode_connection_type(dynamic raw);

  @protected
  DataBits dco_decode_data_bits(dynamic raw);

  @protected
  DebugLogEntry dco_decode_debug_log_entry(dynamic raw);

  @protected
  DeviceInfo dco_decode_device_info(dynamic raw);

  @protected
  DeviceStatus dco_decode_device_status(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FlowControl dco_decode_flow_control(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DebugLogEntry> dco_decode_list_debug_log_entry(dynamic raw);

  @protected
  List<DeviceInfo> dco_decode_list_device_info(dynamic raw);

  @protected
  List<Float64List> dco_decode_list_list_prim_f_64_strict(dynamic raw);

  @protected
  List<PlotPoint> dco_decode_list_plot_point(dynamic raw);

  @protected
  List<PortInfo> dco_decode_list_port_info(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, List<PlotPoint>)> dco_decode_list_record_string_list_plot_point(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DeviceInfo? dco_decode_opt_box_autoadd_device_info(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  Parity dco_decode_parity(dynamic raw);

  @protected
  PlotPoint dco_decode_plot_point(dynamic raw);

  @protected
  PortInfo dco_decode_port_info(dynamic raw);

  @protected
  Protocol dco_decode_protocol(dynamic raw);

  @protected
  (String, List<PlotPoint>) dco_decode_record_string_list_plot_point(
    dynamic raw,
  );

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  StopBits dco_decode_stop_bits(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VirtualInfraStatus dco_decode_virtual_infra_status(dynamic raw);

  @protected
  Map<String, List<PlotPoint>> sse_decode_Map_String_list_plot_point_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DeviceInfo sse_decode_box_autoadd_device_info(SseDeserializer deserializer);

  @protected
  ConnectionType sse_decode_connection_type(SseDeserializer deserializer);

  @protected
  DataBits sse_decode_data_bits(SseDeserializer deserializer);

  @protected
  DebugLogEntry sse_decode_debug_log_entry(SseDeserializer deserializer);

  @protected
  DeviceInfo sse_decode_device_info(SseDeserializer deserializer);

  @protected
  DeviceStatus sse_decode_device_status(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FlowControl sse_decode_flow_control(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DebugLogEntry> sse_decode_list_debug_log_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceInfo> sse_decode_list_device_info(SseDeserializer deserializer);

  @protected
  List<Float64List> sse_decode_list_list_prim_f_64_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<PlotPoint> sse_decode_list_plot_point(SseDeserializer deserializer);

  @protected
  List<PortInfo> sse_decode_list_port_info(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, List<PlotPoint>)> sse_decode_list_record_string_list_plot_point(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DeviceInfo? sse_decode_opt_box_autoadd_device_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Parity sse_decode_parity(SseDeserializer deserializer);

  @protected
  PlotPoint sse_decode_plot_point(SseDeserializer deserializer);

  @protected
  PortInfo sse_decode_port_info(SseDeserializer deserializer);

  @protected
  Protocol sse_decode_protocol(SseDeserializer deserializer);

  @protected
  (String, List<PlotPoint>) sse_decode_record_string_list_plot_point(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  StopBits sse_decode_stop_bits(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VirtualInfraStatus sse_decode_virtual_infra_status(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_Map_String_list_plot_point_None(
    Map<String, List<PlotPoint>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_device_info(
    DeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_type(
    ConnectionType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_data_bits(DataBits self, SseSerializer serializer);

  @protected
  void sse_encode_debug_log_entry(DebugLogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_device_info(DeviceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_device_status(DeviceStatus self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_flow_control(FlowControl self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_debug_log_entry(
    List<DebugLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_info(
    List<DeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_f_64_strict(
    List<Float64List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_plot_point(
    List<PlotPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_port_info(List<PortInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_list_plot_point(
    List<(String, List<PlotPoint>)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_device_info(
    DeviceInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parity(Parity self, SseSerializer serializer);

  @protected
  void sse_encode_plot_point(PlotPoint self, SseSerializer serializer);

  @protected
  void sse_encode_port_info(PortInfo self, SseSerializer serializer);

  @protected
  void sse_encode_protocol(Protocol self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_list_plot_point(
    (String, List<PlotPoint>) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stop_bits(StopBits self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_virtual_infra_status(
    VirtualInfraStatus self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
