// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 连接类型
enum ConnectionType { serial, tcp, usb, ble, wifi }

/// 数据位
enum DataBits { five, six, seven, eight }

/// 设备完整信息 = 配置 + 运行时状态（对外暴露的统一模型）
class DeviceInfo {
  final String id;
  final String name;
  final String deviceType;
  final ConnectionType connectionType;
  final String address;
  final Protocol protocol;
  final bool isVirtual;
  final String? serverInfo;
  final DeviceStatus status;
  final String? lastSeen;
  final String? errorMessage;

  const DeviceInfo({
    required this.id,
    required this.name,
    required this.deviceType,
    required this.connectionType,
    required this.address,
    required this.protocol,
    required this.isVirtual,
    this.serverInfo,
    required this.status,
    this.lastSeen,
    this.errorMessage,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      deviceType.hashCode ^
      connectionType.hashCode ^
      address.hashCode ^
      protocol.hashCode ^
      isVirtual.hashCode ^
      serverInfo.hashCode ^
      status.hashCode ^
      lastSeen.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          deviceType == other.deviceType &&
          connectionType == other.connectionType &&
          address == other.address &&
          protocol == other.protocol &&
          isVirtual == other.isVirtual &&
          serverInfo == other.serverInfo &&
          status == other.status &&
          lastSeen == other.lastSeen &&
          errorMessage == other.errorMessage;
}

/// 设备状态
enum DeviceStatus { disconnected, connecting, connected, error }

/// 流控
enum FlowControl { none, hardware, software }

/// 校验位
enum Parity { none, odd, even }

/// 串口信息（用于 UI 显示）
class PortInfo {
  final String name;
  final String portType;
  final String description;
  final bool isVirtual;

  const PortInfo({
    required this.name,
    required this.portType,
    required this.description,
    required this.isVirtual,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      portType.hashCode ^
      description.hashCode ^
      isVirtual.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PortInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          portType == other.portType &&
          description == other.description &&
          isVirtual == other.isVirtual;
}

/// 通信协议
enum Protocol { raw, modbusRtu, modbusTcp, scpi, csv, private }

/// 停止位
enum StopBits { one, two }
