// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'ringbuffer.dart';

// These functions are ignored because they are not marked as `pub`: `lttb_downsample`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 后台更新线程（在 Rust 端启动）
/// 每 10ms 调用一次 PYRAMID.lock().update()
Future<void> startPyramidUpdateThread() =>
    RustLib.instance.api.crateApiBucketsStartPyramidUpdateThread();

class AtomicU64Array4 extends NonGrowableListView<AtomicU64> {
  static const arraySize = 4;

  @internal
  List<AtomicU64> get inner => _inner;
  final List<AtomicU64> _inner;

  AtomicU64Array4(this._inner)
    : assert(_inner.length == arraySize),
      super(_inner);

  AtomicU64Array4.init(AtomicU64 fill)
    : this(List<AtomicU64>.filled(arraySize, fill));
}

class BTreeMapU64TimeBucketArray4
    extends NonGrowableListView<BTreeMapU64TimeBucket> {
  static const arraySize = 4;

  @internal
  List<BTreeMapU64TimeBucket> get inner => _inner;
  final List<BTreeMapU64TimeBucket> _inner;

  BTreeMapU64TimeBucketArray4(this._inner)
    : assert(_inner.length == arraySize),
      super(_inner);

  BTreeMapU64TimeBucketArray4.init(BTreeMapU64TimeBucket fill)
    : this(List<BTreeMapU64TimeBucket>.filled(arraySize, fill));
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RwLock < BTreeMap < u64 , TimeBucket > >>>
abstract class BTreeMapU64TimeBucket implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TimeBucket>>
abstract class TimeBucket implements RustOpaqueInterface {
  double get first;

  double get last;

  double get max;

  double get min;

  set first(double first);

  set last(double last);

  set max(double max);

  set min(double min);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<TimeBucket> newInstance({required DataPoint point}) =>
      RustLib.instance.api.crateApiBucketsTimeBucketNew(point: point);

  Future<void> update({required DataPoint point});
}

/// 金字塔层级
enum PyramidLevel {
  ms10,
  ms100,
  s1,
  s10;

  /// 获取层级索引
  Future<BigInt> asUsize() =>
      RustLib.instance.api.crateApiBucketsPyramidLevelAsUsize(that: this);

  /// 获取桶宽度（秒）
  Future<double> bucketWidthSeconds() => RustLib.instance.api
      .crateApiBucketsPyramidLevelBucketWidthSeconds(that: this);

  /// 根据时间范围自动选择最合适的层级
  static Future<PyramidLevel> selectForRange({required double timeRange}) =>
      RustLib.instance.api.crateApiBucketsPyramidLevelSelectForRange(
        timeRange: timeRange,
      );
}

/// 时间桶金字塔
/// 使用 BTreeMap 存储桶，按时间戳索引
class TimePyramid {
  /// 四级金字塔
  final BTreeMapU64TimeBucketArray4 levels;

  /// 每个层级的最后更新时间戳（避免重复计算）
  final AtomicU64Array4 lastUpdate;

  const TimePyramid({required this.levels, required this.lastUpdate});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<TimePyramid> newInstance() =>
      RustLib.instance.api.crateApiBucketsTimePyramidNew();

  /// 查询指定时间范围内的数据点（自动选择金字塔层级 + LTTB 降采样）
  /// 性能：< 500µs（即使查询 1 小时数据）
  Future<List<DataPoint>> query({
    required double tStart,
    required double tEnd,
    required int maxPoints,
  }) => RustLib.instance.api.crateApiBucketsTimePyramidQuery(
    that: this,
    tStart: tStart,
    tEnd: tEnd,
    maxPoints: maxPoints,
  );

  /// 更新金字塔（异步，由后台线程定期调用）
  /// 从环形缓冲读取新数据，更新所有层级
  Future<void> update() =>
      RustLib.instance.api.crateApiBucketsTimePyramidUpdate(that: this);

  @override
  int get hashCode => levels.hashCode ^ lastUpdate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimePyramid &&
          runtimeType == other.runtimeType &&
          levels == other.levels &&
          lastUpdate == other.lastUpdate;
}
