// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 启动独立线程接收数据
void startDataReceiver() =>
    RustLib.instance.api.crateApiDataReceiverStartDataReceiver();

/// 停止数据接收器
void stopDataReceiver() =>
    RustLib.instance.api.crateApiDataReceiverStopDataReceiver();

/// 检查数据接收器是否在运行
bool isDataReceiverRunning() =>
    RustLib.instance.api.crateApiDataReceiverIsDataReceiverRunning();
