// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/session/debug_session.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock_mutex`, `spawn_receive_loop`

/// Initialize the Rust logger to output to the debug console window.
/// Called once at app startup.
void debugInitLogger() =>
    RustLib.instance.api.crateApiDebugApiDebugInitLogger();

/// Set the Rust log level at runtime.
/// Levels: "trace", "debug", "info", "warn", "error", "off"
void debugSetLogLevel({required String level}) =>
    RustLib.instance.api.crateApiDebugApiDebugSetLogLevel(level: level);

/// Enable or disable file logging.
void debugSetFileLoggingEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiDebugApiDebugSetFileLoggingEnabled(enabled: enabled);

/// Set the log file path.
void debugSetLogFilePath({required String path}) =>
    RustLib.instance.api.crateApiDebugApiDebugSetLogFilePath(path: path);

/// Get the current log file path.
String debugGetLogFilePath() =>
    RustLib.instance.api.crateApiDebugApiDebugGetLogFilePath();

bool debugSendBytes({required String deviceId, required List<int> data}) =>
    RustLib.instance.api.crateApiDebugApiDebugSendBytes(
      deviceId: deviceId,
      data: data,
    );

bool debugSendString({
  required String deviceId,
  required String text,
  required String lineEnding,
}) => RustLib.instance.api.crateApiDebugApiDebugSendString(
  deviceId: deviceId,
  text: text,
  lineEnding: lineEnding,
);

bool debugSendHex({required String deviceId, required String hexString}) =>
    RustLib.instance.api.crateApiDebugApiDebugSendHex(
      deviceId: deviceId,
      hexString: hexString,
    );

Uint8List? debugReceive({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiDebugReceive(deviceId: deviceId);

List<DebugLogEntry> debugGetLog({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiDebugGetLog(deviceId: deviceId);

List<DebugLogEntry> debugGetLogWithLimit({
  required String deviceId,
  required int maxSize,
}) => RustLib.instance.api.crateApiDebugApiDebugGetLogWithLimit(
  deviceId: deviceId,
  maxSize: maxSize,
);

void debugSetBufferSize({required String deviceId, required int maxSize}) =>
    RustLib.instance.api.crateApiDebugApiDebugSetBufferSize(
      deviceId: deviceId,
      maxSize: maxSize,
    );

bool debugClearLog({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiDebugClearLog(deviceId: deviceId);

bool debugIsConnected({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiDebugIsConnected(deviceId: deviceId);

List<String> debugGetActiveSessions() =>
    RustLib.instance.api.crateApiDebugApiDebugGetActiveSessions();

List<(String, String)> debugGetActiveDeviceNames() =>
    RustLib.instance.api.crateApiDebugApiDebugGetActiveDeviceNames();

/// 启动后台接收循环（供 device_api 的 connectDevice 也调用）
Future<void> startReceiveLoopIfNeeded({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiDebugApiStartReceiveLoopIfNeeded(deviceId: deviceId);

Future<void> stopReceiveLoop({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiStopReceiveLoop(deviceId: deviceId);
