// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/session/debug_session.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock_mutex`, `spawn_receive_loop`

bool debugSendBytes({required String deviceId, required List<int> data}) =>
    RustLib.instance.api.crateApiDebugApiDebugSendBytes(
      deviceId: deviceId,
      data: data,
    );

bool debugSendString({
  required String deviceId,
  required String text,
  required String lineEnding,
}) => RustLib.instance.api.crateApiDebugApiDebugSendString(
  deviceId: deviceId,
  text: text,
  lineEnding: lineEnding,
);

bool debugSendHex({required String deviceId, required String hexString}) =>
    RustLib.instance.api.crateApiDebugApiDebugSendHex(
      deviceId: deviceId,
      hexString: hexString,
    );

/// 手动接收（备用，主要靠后台 receive loop 自动记录）
Uint8List? debugReceive({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiDebugReceive(deviceId: deviceId);

List<DebugLogEntry> debugGetLog({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiDebugGetLog(deviceId: deviceId);

/// 获取日志（带缓冲区大小限制）
List<DebugLogEntry> debugGetLogWithLimit({
  required String deviceId,
  required int maxSize,
}) => RustLib.instance.api.crateApiDebugApiDebugGetLogWithLimit(
  deviceId: deviceId,
  maxSize: maxSize,
);

/// 设置缓冲区大小
void debugSetBufferSize({required String deviceId, required int maxSize}) =>
    RustLib.instance.api.crateApiDebugApiDebugSetBufferSize(
      deviceId: deviceId,
      maxSize: maxSize,
    );

bool debugClearLog({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiDebugClearLog(deviceId: deviceId);

bool debugIsConnected({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiDebugIsConnected(deviceId: deviceId);

List<String> debugGetActiveSessions() =>
    RustLib.instance.api.crateApiDebugApiDebugGetActiveSessions();

/// 返回已连接设备的 (id, name) 列表，供 Lua UI 使用
List<(String, String)> debugGetActiveDeviceNames() =>
    RustLib.instance.api.crateApiDebugApiDebugGetActiveDeviceNames();

/// 启动后台接收循环（供 device_api 的 connectDevice 也调用）
Future<void> startReceiveLoopIfNeeded({required String deviceId}) => RustLib
    .instance
    .api
    .crateApiDebugApiStartReceiveLoopIfNeeded(deviceId: deviceId);

Future<void> stopReceiveLoop({required String deviceId}) =>
    RustLib.instance.api.crateApiDebugApiStopReceiveLoop(deviceId: deviceId);
