// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/device/models.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_persistence_path`, `lock_mutex`, `parse_connection_type`, `parse_protocol`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PersistedDevice`

/// 获取所有支持的协议
List<String> getSupportedProtocols() =>
    RustLib.instance.api.crateApiDeviceApiGetSupportedProtocols();

/// 获取所有设备列表
List<DeviceInfo> listDevices() =>
    RustLib.instance.api.crateApiDeviceApiListDevices();

/// 获取单个设备信息
DeviceInfo? getDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiDeviceApiGetDevice(deviceId: deviceId);

/// 添加串口设备
/// address 格式: port:baudRate:dataBits:stopBits:parity:flowControl:receiveTimeoutMs:dtr:rts:bk
DeviceInfo addSerialDevice({
  required String name,
  required String port,
  required int baudRate,
  required Protocol protocol,
  required DataBits dataBits,
  required StopBits stopBits,
  required Parity parity,
  required FlowControl flowControl,
  required BigInt receiveTimeoutMs,
  required bool dtrEnabled,
  required bool rtsEnabled,
  required bool breakEnabled,
}) => RustLib.instance.api.crateApiDeviceApiAddSerialDevice(
  name: name,
  port: port,
  baudRate: baudRate,
  protocol: protocol,
  dataBits: dataBits,
  stopBits: stopBits,
  parity: parity,
  flowControl: flowControl,
  receiveTimeoutMs: receiveTimeoutMs,
  dtrEnabled: dtrEnabled,
  rtsEnabled: rtsEnabled,
  breakEnabled: breakEnabled,
);

/// 添加 TCP 设备
DeviceInfo addTcpDevice({
  required String name,
  required String host,
  required int port,
  required Protocol protocol,
}) => RustLib.instance.api.crateApiDeviceApiAddTcpDevice(
  name: name,
  host: host,
  port: port,
  protocol: protocol,
);

/// 更新设备配置
Future<bool> updateDevice({
  required String deviceId,
  required String name,
  required String address,
  required Protocol protocol,
}) => RustLib.instance.api.crateApiDeviceApiUpdateDevice(
  deviceId: deviceId,
  name: name,
  address: address,
  protocol: protocol,
);

/// 删除设备
Future<bool> removeDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiDeviceApiRemoveDevice(deviceId: deviceId);

/// 串口扫描（带缓存，纯 Rust serialport crate 实现）
List<PortInfo> scanSerialPorts() =>
    RustLib.instance.api.crateApiDeviceApiScanSerialPorts();

/// 连接设备
Future<bool> connectDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiDeviceApiConnectDevice(deviceId: deviceId);

/// 断开设备
Future<bool> disconnectDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiDeviceApiDisconnectDevice(deviceId: deviceId);

/// 查询设备是否已连接
bool isDeviceConnected({required String deviceId}) =>
    RustLib.instance.api.crateApiDeviceApiIsDeviceConnected(deviceId: deviceId);

/// 设置 DTR 信号
bool serialSetDtr({required String deviceId, required bool level}) => RustLib
    .instance
    .api
    .crateApiDeviceApiSerialSetDtr(deviceId: deviceId, level: level);

/// 设置 RTS 信号
bool serialSetRts({required String deviceId, required bool level}) => RustLib
    .instance
    .api
    .crateApiDeviceApiSerialSetRts(deviceId: deviceId, level: level);

/// 设置 Break 信号（开始发送 Break）
bool serialSetBreak({required String deviceId}) =>
    RustLib.instance.api.crateApiDeviceApiSerialSetBreak(deviceId: deviceId);

/// 清除 Break 信号（停止发送 Break）
bool serialClearBreak({required String deviceId}) =>
    RustLib.instance.api.crateApiDeviceApiSerialClearBreak(deviceId: deviceId);

/// 加载演示设备（用于 UI 展示）
void loadDemoDevices() =>
    RustLib.instance.api.crateApiDeviceApiLoadDemoDevices();

/// 加载虚拟设备（TCP-SCPI-Demo, Serial-SCPI-Demo）
void loadVirtualDevices() =>
    RustLib.instance.api.crateApiDeviceApiLoadVirtualDevices();

/// 清除演示设备
Future<void> clearDemoDevices() =>
    RustLib.instance.api.crateApiDeviceApiClearDemoDevices();

/// 保存设备到 JSON 文件
void saveDevices() => RustLib.instance.api.crateApiDeviceApiSaveDevices();

/// 从 JSON 文件加载设备，返回加载的设备数量
int loadPersistedDevices() =>
    RustLib.instance.api.crateApiDeviceApiLoadPersistedDevices();

/// 解析 CSV 协议数据行，返回通道值数组
/// 返回 JSON 字符串以便 FRB 支持
String? parseCsvData({required String line}) =>
    RustLib.instance.api.crateApiDeviceApiParseCsvData(line: line);

/// 批量解析 CSV 数据（多行），返回每行的通道值数组
List<Float64List> parseCsvBatch({required String data}) =>
    RustLib.instance.api.crateApiDeviceApiParseCsvBatch(data: data);
