// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 注册 Plot 设备
/// channels: 通道名称列表,如 ["voltage", "current", "power"]
void plotRegisterDevice({
  required String deviceId,
  required List<String> channels,
}) => RustLib.instance.api.crateApiPlotApiPlotRegisterDevice(
  deviceId: deviceId,
  channels: channels,
);

/// 注销 Plot 设备
void plotUnregisterDevice({required String deviceId}) => RustLib.instance.api
    .crateApiPlotApiPlotUnregisterDevice(deviceId: deviceId);

/// 添加单个数据点
void plotPushData({
  required String deviceId,
  required String channel,
  required double timestampMs,
  required double value,
}) => RustLib.instance.api.crateApiPlotApiPlotPushData(
  deviceId: deviceId,
  channel: channel,
  timestampMs: timestampMs,
  value: value,
);

/// 批量添加数据点(从协议解析)
void plotPushBatch({
  required String deviceId,
  required List<String> channels,
  required double timestampMs,
  required List<double> values,
}) => RustLib.instance.api.crateApiPlotApiPlotPushBatch(
  deviceId: deviceId,
  channels: channels,
  timestampMs: timestampMs,
  values: values,
);

/// 从 CSV 协议数据添加
void plotPushCsv({
  required String deviceId,
  String? prefix,
  required double timestampMs,
  required List<double> values,
}) => RustLib.instance.api.crateApiPlotApiPlotPushCsv(
  deviceId: deviceId,
  prefix: prefix,
  timestampMs: timestampMs,
  values: values,
);

/// 获取通道数据
List<PlotPoint> plotGetChannelData({
  required String deviceId,
  required String channel,
}) => RustLib.instance.api.crateApiPlotApiPlotGetChannelData(
  deviceId: deviceId,
  channel: channel,
);

/// 获取设备所有通道数据
Map<String, List<PlotPoint>> plotGetAllChannels({required String deviceId}) =>
    RustLib.instance.api.crateApiPlotApiPlotGetAllChannels(deviceId: deviceId);

/// 获取设备的通道列表
List<String> plotGetChannels({required String deviceId}) =>
    RustLib.instance.api.crateApiPlotApiPlotGetChannels(deviceId: deviceId);

/// 清空设备数据
void plotClearDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiPlotApiPlotClearDevice(deviceId: deviceId);

/// 获取当前样本计数器值
BigInt plotGetCounter() => RustLib.instance.api.crateApiPlotApiPlotGetCounter();

/// 重置样本计数器
void plotClearCounter() =>
    RustLib.instance.api.crateApiPlotApiPlotClearCounter();

/// 从计数器值添加 CSV 数据(X轴使用计数器而非时间戳)
void plotPushCsvCounter({
  required String deviceId,
  String? prefix,
  required List<double> values,
}) => RustLib.instance.api.crateApiPlotApiPlotPushCsvCounter(
  deviceId: deviceId,
  prefix: prefix,
  values: values,
);

/// 获取当前时间戳(毫秒)
double plotGetTimestampMs() =>
    RustLib.instance.api.crateApiPlotApiPlotGetTimestampMs();

/// 获取通道视口数据:裁剪 + 降采样
List<PlotPoint> plotGetChannelViewportData({
  required String deviceId,
  required String channel,
  required double xMin,
  required double xMax,
  required int maxPoints,
}) => RustLib.instance.api.crateApiPlotApiPlotGetChannelViewportData(
  deviceId: deviceId,
  channel: channel,
  xMin: xMin,
  xMax: xMax,
  maxPoints: maxPoints,
);

/// 获取通道的最新数据点
///
/// # 参数
/// - `device_id`: 设备 ID
/// - `channel`: 通道名称
///
/// # 返回
/// 最新数据点（如果没有数据，返回空列表）
List<PlotPoint> plotGetChannelLatestData({
  required String deviceId,
  required String channel,
}) => RustLib.instance.api.crateApiPlotApiPlotGetChannelLatestData(
  deviceId: deviceId,
  channel: channel,
);

/// 设置 Plot 数据缓冲区容量
void plotSetBufferCapacity({required BigInt capacity}) => RustLib.instance.api
    .crateApiPlotApiPlotSetBufferCapacity(capacity: capacity);

/// 获取 Plot 数据缓冲区容量
BigInt plotGetBufferCapacity() =>
    RustLib.instance.api.crateApiPlotApiPlotGetBufferCapacity();

/// 数据点(FRB 兼容)
class PlotPoint {
  final double timestampMs;
  final double value;

  const PlotPoint({required this.timestampMs, required this.value});

  @override
  int get hashCode => timestampMs.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlotPoint &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          value == other.value;
}
