// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LockFreeRingBuffer>>
abstract class LockFreeRingBuffer implements RustOpaqueInterface {
  /// 获取容量
  Future<BigInt> capacity();

  /// 读取最新 N 个数据点（无锁）
  /// 返回 (数据点指针, 数据点数)
  /// 调用者必须确保在使用期间不调用 push()
  Future<(ConstDataPoint, BigInt)> getLatest({required BigInt n});

  /// 读取指定范围的数据（无锁）
  /// 用于视口查询
  /// 返回 (数据点指针, 数据点数, 是否换行)
  /// 注意：返回的是环形缓冲内的连续内存，可能需要两次读取（wrap around）
  Future<(ConstDataPoint, BigInt, bool)> getRange({
    required BigInt start,
    required BigInt end,
  });

  /// 获取当前读索引（用于视口查询）
  Future<BigInt> getReadIdx();

  /// 获取当前写索引（用于视口查询）
  Future<BigInt> getWriteIdx();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// 创建新的无锁环形缓冲
  /// capacity 必须是 2 的幂（内部会向上取整）
  static Future<LockFreeRingBuffer> newInstance({required BigInt capacity}) =>
      RustLib.instance.api.crateApiRingbufferLockFreeRingBufferNew(
        capacity: capacity,
      );

  /// 写入单个数据点（无锁）
  /// 返回写入位置（用于调试）
  Future<BigInt> push({required DataPoint point});

  /// 批量写入数据点（无锁）
  /// 用于协议解析后批量推送
  Future<BigInt> pushBatch({required List<DataPoint> points});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<* const DataPoint>>
abstract class ConstDataPoint implements RustOpaqueInterface {}

/// 数据点（16字节对齐）
/// 使用 f64 而非 f32，因为时间戳需要微秒精度
class DataPoint {
  final double timestamp;
  final double value;

  const DataPoint({required this.timestamp, required this.value});

  @override
  int get hashCode => timestamp.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataPoint &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          value == other.value;
}
