// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 虚拟基础设施状态
class VirtualInfraStatus {
  final bool tcpScpiRunning;
  final String tcpScpiAddress;
  final bool virtualSerialRunning;
  final String virtualSerialPorts;

  const VirtualInfraStatus({
    required this.tcpScpiRunning,
    required this.tcpScpiAddress,
    required this.virtualSerialRunning,
    required this.virtualSerialPorts,
  });

  @override
  int get hashCode =>
      tcpScpiRunning.hashCode ^
      tcpScpiAddress.hashCode ^
      virtualSerialRunning.hashCode ^
      virtualSerialPorts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VirtualInfraStatus &&
          runtimeType == other.runtimeType &&
          tcpScpiRunning == other.tcpScpiRunning &&
          tcpScpiAddress == other.tcpScpiAddress &&
          virtualSerialRunning == other.virtualSerialRunning &&
          virtualSerialPorts == other.virtualSerialPorts;
}
