// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 调试日志条目
class DebugLogEntry {
  final PlatformInt64 timestamp;
  final String direction;
  final Uint8List data;
  final String display;

  const DebugLogEntry({
    required this.timestamp,
    required this.direction,
    required this.data,
    required this.display,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^
      direction.hashCode ^
      data.hashCode ^
      display.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DebugLogEntry &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          direction == other.direction &&
          data == other.data &&
          display == other.display;
}
